# optional file
resources:
- repo: self

queue:
  name: Hosted Ubuntu 1604
  demands: maven

steps:
- task: Maven@3
  displayName: 'Maven Build'

- task: Docker@1
  displayName: 'Docker Build'
  inputs:
    azureSubscriptionEndpoint: 'Microsoft Azure Enterprise (7854e362-1746-46b4-8d2c-6829fbee517e)'
    azureContainerRegistry: tsivbcr.azurecr.io

- task: Docker@1
  displayName: 'Docker Push'
  inputs:
    azureSubscriptionEndpoint: 'Microsoft Azure Enterprise (7854e362-1746-46b4-8d2c-6829fbee517e)'
    azureContainerRegistry: tsivbcr.azurecr.io
    command: 'Push an image'