apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - name: config
        image: tsivb/config:#{Release.Artifacts.Image.BuildId}#