spring:
  activemq:
    brokerUrl: tcp://localhost:61616
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ping;MODE=PostgreSQL
    username: sa
    password:
azure:
  servicebus:
    connection: none